filename: frontend-web-dev.collection.yml
id: frontend-web-dev
name: Frontend Web Development
description: "Essential prompts, instructions, and chat modes for modern frontend web development including React, Angular, Vue, TypeScript, and CSS frameworks."
tags:
  - frontend
  - web
  - react
  - typescript
  - javascript
  - css
  - html
  - angular
  - vue
items:
  - path: agents/expert-react-frontend-engineer.agent.md
    kind: agent
  - path: agents/expert-nextjs-developer.agent.md
    kind: agent
  - path: agents/electron-angular-native.agent.md
    kind: agent
  - path: instructions/reactjs.instructions.md
    kind: instruction
  - path: instructions/nextjs.instructions.md
    kind: instruction
  - path: instructions/nextjs-tailwind.instructions.md
    kind: instruction
  - path: instructions/nodejs-javascript-vitest.instructions.md
    kind: instruction
  - path: prompts/playwright-explore-website.prompt.md
    kind: prompt
  - path: prompts/playwright-generate-test.prompt.md
    kind: prompt
display: {}
