[build]
# This is the command that Netlify will run to build the site. 
command = "npm run build"
# This is the directory that Netlify will publish. 
publish = "out"

[[redirects]]
from = "/admin/*"
to = "/admin/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
# This is the command that Netlify Dev will run to start the development server. 
command = "npm run dev"
# This is the port that the development server will run on. 
targetPort = 3000
publish = "dev"
autoLaunch = true
