[build]
# This is the command that Netlify will run to build the site.
command = "npm run build"
# This is the directory that Netlify will publish.
publish = "out"

[[redirects]]
from = "/admin/*"
to = "/admin/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
command = "npm run dev"
targetPort = 3000
publish = "dev"
autoLaunch = true

# This is to fix the issue with Netlify:
# The following Node.js modules use dynamic expressions to include files: - mongodb
#  Because files included with dynamic expressions aren't guaranteed to be available at build time, the build may fail.
[functions]
external_node_modules = ["mongodb"]
