[build]
# This is the command that Netlify will run to build the site.
command = "yarn build"
# This is the directory that Netlify will publish.
publish = ".next"

# All admin requests should go to admin/index because it's a single page app.
[[redirects]]
from = "/admin/*"
to = "/admin/index.html"
status = 200

[dev]
command = "yarn dev"
targetPort = 3000
publish = ".next"
autoLaunch = true

# This is to fix an issue with Netlify:
# The following Node.js modules use dynamic expressions to include files: - mongodb
#  Because files included with dynamic expressions aren't guaranteed to be available at build time, the build may fail.
[functions]
external_node_modules = ["mongodb"]
