[build]
command = "printenv && ng build --configuration production"
publish = "dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev]
command = "ng serve"
targetPort = 4200
publish = "dev"
autoLaunch = true
