/**
 * ItemAddForm
 * Updated: 05/13/2025
 * Author: Deej Potter
 * Description: Form component for adding new items to the shipping calculator.
 * Handles input validation and item creation with proper dimensioning.
 * Enhanced with Bootstrap styling, improved validation, and better user feedback.
 */

"use client";
import React, { useState } from "react";
import ShippingItem from "@/types/box-shipping-calculator/ShippingItem";
import { Plus, RotateCcw, PenTool } from "lucide-react"; // Icons for better UX

interface ItemAddFormProps {
  onAddItem: (item: ShippingItem) => void;
}

export default function ItemAddForm({ onAddItem }: ItemAddFormProps) {
  // State for form fields
  const [name, setName] = useState("");
  const [sku, setSku] = useState("");
  const [length, setLength] = useState("");
  const [width, setWidth] = useState("");
  const [height, setHeight] = useState("");
  const [weight, setWeight] = useState("");

  // State for form validation
  const [validated, setValidated] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isTouched, setIsTouched] = useState({
    name: false,
    length: false,
    width: false,
    height: false,
    weight: false,
  });

  /**
   * Reset form to initial state
   * Clears all input fields and validation state
   */
  const resetForm = () => {
    setName("");
    setSku("");
    setLength("");
    setWidth("");
    setHeight("");
    setWeight("");
    setValidated(false);
    setIsTouched({
      name: false,
      length: false,
      width: false,
      height: false,
      weight: false,
    });
  };

  /**
   * Fill form with sample dimensions
   * Helps users by providing common dimension templates
   * @param preset The preset name to apply
   */
  const applyDimensionPreset = (preset: string) => {
    switch (preset) {
      case "small":
        setLength("50");
        setWidth("50");
        setHeight("10");
        setWeight("5");
        break;
      case "medium":
        setLength("200");
        setWidth("150");
        setHeight("50");
        setWeight("500");
        break;
      case "large":
        setLength("300");
        setWidth("200");
        setHeight("100");
        setWeight("3000");
        break;
      default:
        break;
    }

    // Mark all dimension fields as touched
    setIsTouched((prev) => ({
      ...prev,
      length: true,
      width: true,
      height: true,
      weight: true,
    }));
  };

  /**
   * Handle form submission with validation
   * Creates a new shipping item and passes it to the parent component
   * Provides visual feedback during submission
   * @param e Form submit event
   */
  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    // Mark form as validated to show validation feedback
    setValidated(true);

    const form = e.currentTarget;
    if (form.checkValidity() === false) {
      e.stopPropagation();
      return;
    }

    setIsSubmitting(true);

    // Create new item with unique ID
    const newItem: ShippingItem = {
      _id: null, // ID will be generated by the database
      name, // Use the name provided in the form
      sku: sku || "", // Use empty string if SKU is not provided
      length: Math.round(Number(length)),
      width: Math.round(Number(width)),
      height: Math.round(Number(height)),
      weight: Math.round(Number(weight)),
      deletedAt: null,
      updatedAt: new Date(),
    };

    // Add item and reset form with a small delay to show feedback
    setTimeout(() => {
      onAddItem(newItem);
      resetForm();
      setIsSubmitting(false);
    }, 300);
  };

  return (
    <form
      onSubmit={handleSubmit}
      className={validated ? "was-validated" : ""}
      noValidate
    >
      <div className="bg-white border border-gray-200 rounded mb-4">
        <div className="bg-gray-50 px-4 py-3 border-b border-gray-200">
          <h5 className="text-lg font-semibold mb-0">
            <PenTool size={16} className="inline mr-2" />
            Add New Item
          </h5>
        </div>
        <div className="p-4">
          <div className="mb-3">
            <label
              htmlFor="item-name"
              className="block text-sm font-medium text-gray-700 mb-1"
            >
              Name:
            </label>
            <input
              id="item-name"
              type="text"
              value={name}
              onChange={(e) => setName(e.target.value)}
              onBlur={() => setIsTouched((prev) => ({ ...prev, name: true }))}
              required
              className={`w-full px-3 py-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                isTouched.name && !name ? "border-red-500" : "border-gray-300"
              }`}
              placeholder="Enter item name"
            />
            {isTouched.name && !name && (
              <div className="text-red-500 text-sm mt-1">
                Please provide an item name.
              </div>
            )}
          </div>

          <div className="mb-3">
            <label
              htmlFor="item-sku"
              className="block text-sm font-medium text-gray-700 mb-1"
            >
              SKU:
            </label>
            <input
              id="item-sku"
              type="text"
              value={sku}
              onChange={(e) => setSku(e.target.value)}
              className="w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
              placeholder="Enter SKU"
            />
          </div>

          {/* Dimension Presets */}
          <div className="mb-3">
            <label className="block text-sm font-medium text-gray-700 mb-1">
              Dimension Presets:
            </label>
            <div className="flex gap-2">
              <button
                type="button"
                className="border border-gray-500 text-gray-500 px-3 py-1 text-sm hover:bg-gray-500 hover:text-white"
                onClick={() => applyDimensionPreset("small")}
              >
                Small Item
              </button>
              <button
                type="button"
                className="border border-gray-500 text-gray-500 px-3 py-1 text-sm hover:bg-gray-500 hover:text-white"
                onClick={() => applyDimensionPreset("medium")}
              >
                Medium Item
              </button>
              <button
                type="button"
                className="border border-gray-500 text-gray-500 px-3 py-1 text-sm hover:bg-gray-500 hover:text-white"
                onClick={() => applyDimensionPreset("large")}
              >
                Large Item
              </button>
            </div>
            <div className="text-gray-600 text-sm mt-1">
              Click a preset to quickly fill dimension fields
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-3">
            <div>
              <label
                htmlFor="item-length"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Length:
              </label>
              <div className="flex">
                <input
                  id="item-length"
                  type="number"
                  value={length}
                  onChange={(e) => {
                    const rawValue = e.target.value;
                    const numValue = Number(rawValue);
                    if (!isNaN(numValue) && rawValue) {
                      setLength(String(Math.round(numValue)));
                    } else {
                      setLength(rawValue);
                    }
                  }}
                  onBlur={() =>
                    setIsTouched((prev) => ({ ...prev, length: true }))
                  }
                  required
                  min="1"
                  step="1"
                  pattern="[0-9]*"
                  className={`flex-1 px-3 py-2 border rounded-l focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                    isTouched.length && (!length || Number(length) < 1)
                      ? "border-red-500"
                      : "border-gray-300"
                  }`}
                  placeholder="Length"
                />
                <span className="inline-flex items-center px-3 bg-gray-200 border border-l-0 border-gray-300 rounded-r">
                  mm
                </span>
                {isTouched.length && (!length || Number(length) < 1) && (
                  <div className="text-red-500 text-sm mt-1">
                    Please provide a valid length (greater than 0).
                  </div>
                )}
              </div>
            </div>

            <div>
              <label
                htmlFor="item-width"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Width:
              </label>
              <div className="flex">
                <input
                  id="item-width"
                  type="number"
                  value={width}
                  onChange={(e) => {
                    const rawValue = e.target.value;
                    const numValue = Number(rawValue);
                    if (!isNaN(numValue) && rawValue) {
                      setWidth(String(Math.round(numValue)));
                    } else {
                      setWidth(rawValue);
                    }
                  }}
                  onBlur={() =>
                    setIsTouched((prev) => ({ ...prev, width: true }))
                  }
                  required
                  min="1"
                  step="1"
                  pattern="[0-9]*"
                  className={`flex-1 px-3 py-2 border rounded-l focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                    isTouched.width && (!width || Number(width) < 1)
                      ? "border-red-500"
                      : "border-gray-300"
                  }`}
                  placeholder="Width"
                />
                <span className="inline-flex items-center px-3 bg-gray-200 border border-l-0 border-gray-300 rounded-r">
                  mm
                </span>
                {isTouched.width && (!width || Number(width) < 1) && (
                  <div className="text-red-500 text-sm mt-1">
                    Please provide a valid width (greater than 0).
                  </div>
                )}
              </div>
            </div>

            <div>
              <label
                htmlFor="item-height"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Height:
              </label>
              <div className="flex">
                <input
                  id="item-height"
                  type="number"
                  value={height}
                  onChange={(e) => {
                    const rawValue = e.target.value;
                    const numValue = Number(rawValue);
                    if (!isNaN(numValue) && rawValue) {
                      setHeight(String(Math.round(numValue)));
                    } else {
                      setHeight(rawValue);
                    }
                  }}
                  onBlur={() =>
                    setIsTouched((prev) => ({ ...prev, height: true }))
                  }
                  required
                  min="1"
                  step="1"
                  pattern="[0-9]*"
                  className={`flex-1 px-3 py-2 border rounded-l focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                    isTouched.height && (!height || Number(height) < 1)
                      ? "border-red-500"
                      : "border-gray-300"
                  }`}
                  placeholder="Height"
                />
                <span className="inline-flex items-center px-3 bg-gray-200 border border-l-0 border-gray-300 rounded-r">
                  mm
                </span>
                {isTouched.height && (!height || Number(height) < 1) && (
                  <div className="text-red-500 text-sm mt-1">
                    Please provide a valid height (greater than 0).
                  </div>
                )}
              </div>
            </div>

            <div>
              <label
                htmlFor="item-weight"
                className="block text-sm font-medium text-gray-700 mb-1"
              >
                Weight:
              </label>
              <div className="flex">
                <input
                  id="item-weight"
                  type="number"
                  value={weight}
                  onChange={(e) => {
                    const rawValue = e.target.value;
                    const numValue = Number(rawValue);
                    if (!isNaN(numValue) && rawValue) {
                      setWeight(String(Math.round(numValue)));
                    } else {
                      setWeight(rawValue);
                    }
                  }}
                  onBlur={() =>
                    setIsTouched((prev) => ({ ...prev, weight: true }))
                  }
                  required
                  min="1"
                  step="1"
                  pattern="[0-9]*"
                  className={`flex-1 px-3 py-2 border rounded-l focus:outline-none focus:ring-2 focus:ring-blue-500 ${
                    isTouched.weight && (!weight || Number(weight) < 1)
                      ? "border-red-500"
                      : "border-gray-300"
                  }`}
                  placeholder="Weight"
                />
                <span className="inline-flex items-center px-3 bg-gray-200 border border-l-0 border-gray-300 rounded-r">
                  g
                </span>
                {isTouched.weight && (!weight || Number(weight) < 1) && (
                  <div className="text-red-500 text-sm mt-1">
                    Please provide a valid weight (greater than 0).
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
        <div className="bg-gray-50 px-4 py-3 border-t border-gray-200 rounded-b">
          <div className="flex gap-2">
            <button
              type="submit"
              disabled={isSubmitting}
              className="bg-blue-500 text-white px-4 py-2 hover:bg-blue-600 flex-1 disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {isSubmitting ? (
                <>
                  <div className="inline-block animate-spin border-2 border-white border-t-transparent rounded-full w-4 h-4 mr-2" />
                  Adding...
                </>
              ) : (
                <>
                  <Plus size={16} className="inline mr-1" />
                  Add Item
                </>
              )}
            </button>
            <button
              type="button"
              onClick={resetForm}
              className="border border-gray-500 text-gray-500 px-4 py-2 hover:bg-gray-500 hover:text-white"
            >
              <RotateCcw size={16} className="inline" />
              <span className="hidden md:inline ml-1">Reset</span>
            </button>
          </div>
        </div>
      </div>
    </form>
  );
}
