backend:
  name: git-gateway
  branch: master

media_folder: "assets/cms-uploads"

collections:
  - name: "websites"
    label: "Websites"
    folder: "_websites"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      # additional fields...
  
  - name: "funProjects"
    label: "Fun Projects"
    folder: "_funProjects"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      # additional fields...
  
  - name: "games"
    label: "Games"
    folder: "_games"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Externally Hosted", name: "externallyHosted", widget: "boolean", required: false}
      - {label: "External Link", name: "externalLink", widget: "string", required: false}
      - {label: "Internal Path", name: "internalPath", widget: "string", required: false}
      # additional fields...
